export const gregorskillData = {
    LCBGregor: [
        { skillName: "Swipe", icon: "IDs/Gregor/Icons/LCB/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Jag", icon: "IDs/Gregor/Icons/LCB/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Chop Up", icon: "IDs/Gregor/Icons/LCB/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Guard", icon: "IDs/Gregor/Icons/LCB/Defense.webp", skillNum: "Defense" },
    ],
    KurokumoGregor: [
        { skillName: "Lenticular Rend", icon: "IDs/Gregor/Icons/Kurokumo/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Shadow Cloud", icon: "IDs/Gregor/Icons/Kurokumo/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Shadowcloud Shattercleave", icon: "IDs/Gregor/Icons/Kurokumo/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Guard", icon: "IDs/Gregor/Icons/Kurokumo/Defense.webp", skillNum: "Defense" },
    ],
    LiuGregor: [
        { skillName: "Single-point Stab", icon: "IDs/Gregor/Icons/Liu/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Rush Down", icon: "IDs/Gregor/Icons/Liu/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Perfected Palm Strike", icon: "IDs/Gregor/Icons/Liu/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Guard", icon: "IDs/Gregor/Icons/Liu/Defense.webp", skillNum: "Defense" },
    ],
    RBGregor: [
        { skillName: "Keep It Fresh", icon: "IDs/Gregor/Icons/RB/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "You Fresh Enough?", icon: "IDs/Gregor/Icons/RB/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Butcher Viand", icon: "IDs/Gregor/Icons/RB/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Guard", icon: "IDs/Gregor/Icons/RB/Defense.webp", skillNum: "Defense" },
    ],
    RosespannerGregor: [
        { skillName: "Rev Up", icon: "IDs/Gregor/Icons/Rosespanner/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Grease Chains", icon: "IDs/Gregor/Icons/Rosespanner/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Let's Grind 'Em", icon: "IDs/Gregor/Icons/Rosespanner/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Guard", icon: "IDs/Gregor/Icons/Rosespanner/Defense.webp", skillNum: "Defense" },
    ],
    DawnGregor: [
        { skillName: "Flash of Sunup", icon: "IDs/Gregor/Icons/Dawn/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Sunset Blade", icon: "IDs/Gregor/Icons/Dawn/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Dawnsplitter", icon: "IDs/Gregor/Icons/Dawn/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Crack of Dawn", icon: "IDs/Gregor/Icons/Dawn/Skill3_2.webp", skillNum: "Skill 3-2" },
        { skillName: "Guardian", icon: "IDs/Gregor/Icons/Dawn/Defense.webp", skillNum: "Defense" },
        { skillName: "Heat Haze", icon: "IDs/Gregor/Icons/Dawn/Defense2.webp", skillNum: "Defense 2" },
    ],
    EdgarGregor: [
        { skillName: "Sabre Slash", icon: "IDs/Gregor/Icons/Edgar/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Remise", icon: "IDs/Gregor/Icons/Edgar/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Nightmare Hunt", icon: "IDs/Gregor/Icons/Edgar/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Do You Wish to Weep?", icon: "IDs/Gregor/Icons/Edgar/Defense.webp", skillNum: "Defense" },
    ],
    FirefistGregor: [
        { skillName: "Flamethrow", icon: "IDs/Gregor/Icons/Firefist/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "I'll burn away every last drop of your filthy blood", icon: "IDs/Gregor/Icons/Firefist/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Firefist", icon: "IDs/Gregor/Icons/Firefist/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "I have to keep going for big sis", icon: "IDs/Gregor/Icons/Firefist/Defense.webp", skillNum: "Defense" },
    ],
    GCorpGregor: [
        { skillName: "Hack", icon: "IDs/Gregor/Icons/GCorp/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Dismember", icon: "IDs/Gregor/Icons/GCorp/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Eviscerate", icon: "IDs/Gregor/Icons/GCorp/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Guard", icon: "IDs/Gregor/Icons/GCorp/Defense.webp", skillNum: "Defense" },
    ],
    HeishouGregor: [
        { skillName: "Snake Fang", icon: "IDs/Gregor/Icons/Heishou/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Blindsiding Cleave", icon: "IDs/Gregor/Icons/Heishou/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Serpentshear Puncturing Arm", icon: "IDs/Gregor/Icons/Heishou/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Reversal Kick", icon: "IDs/Gregor/Icons/Heishou/Defense.webp", skillNum: "Defense" },
    ],
    LCEGregor: [
        { skillName: "Electric Release", icon: "IDs/Gregor/Icons/LCE/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "DC Inversion", icon: "IDs/Gregor/Icons/LCE/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "High-voltage Current Discharge", icon: "IDs/Gregor/Icons/LCE/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Maximum Output - Ultra High-voltage Current Discharge", icon: "IDs/Gregor/Icons/LCE/Skill3_2.webp", skillNum: "Skill 3-2" },
        { skillName: "This E.G.O Gift's Defensive Capability is Uniquely Superior", icon: "IDs/Gregor/Icons/LCE/Defense.webp", skillNum: "Defense" },
    ],
    LampGregor: [
        { skillName: "Intense Stare: Zero Range", icon: "IDs/Gregor/Icons/Lamp/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Destroy the Visible with the Invisible", icon: "IDs/Gregor/Icons/Lamp/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Salvation for those Enchanted by the Lamp", icon: "IDs/Gregor/Icons/Lamp/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "The Wick of Burned Feathers", icon: "IDs/Gregor/Icons/Lamp/Defense.webp", skillNum: "Defense" },
    ],
    NightGregor: [
        { skillName: "Gap Attack", icon: "IDs/Gregor/Icons/Night/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Mercé", icon: "IDs/Gregor/Icons/Night/Skill1_2.webp", skillNum: "Skill 1-2" },
        { skillName: "Stiletto Doppio", icon: "IDs/Gregor/Icons/Night/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Execution", icon: "IDs/Gregor/Icons/Night/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "The Night's Awl", icon: "IDs/Gregor/Icons/Night/Skill3_2.webp", skillNum: "Skill 3-2" },
        { skillName: "Dire Straits", icon: "IDs/Gregor/Icons/Night/Defense.webp", skillNum: "Defense" },
    ],
    PriestGregor: [
        { skillName: "Sacrifice for the Family", icon: "IDs/Gregor/Icons/Priest/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Suffocating Guilt", icon: "IDs/Gregor/Icons/Priest/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "The Unforgivable Sin", icon: "IDs/Gregor/Icons/Priest/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Faded Patience", icon: "IDs/Gregor/Icons/Priest/Defense.webp", skillNum: "Defense" },
    ],
    TwinhookGregor: [
        { skillName: "Negotiation Start", icon: "IDs/Gregor/Icons/Twinhook/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Unilateral Business", icon: "IDs/Gregor/Icons/Twinhook/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Foregone Conclusion", icon: "IDs/Gregor/Icons/Twinhook/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "Take a Breather", icon: "IDs/Gregor/Icons/Twinhook/Defense.webp", skillNum: "Defense" },
    ],
    ZweiGregor: [
        { skillName: "Standoff", icon: "IDs/Gregor/Icons/Zwei/Skill1.webp", skillNum: "Skill 1" },
        { skillName: "Flexible Suppression", icon: "IDs/Gregor/Icons/Zwei/Skill2.webp", skillNum: "Skill 2" },
        { skillName: "Guardian", icon: "IDs/Gregor/Icons/Zwei/Skill3.webp", skillNum: "Skill 3" },
        { skillName: "The Best Defense", icon: "IDs/Gregor/Icons/Zwei/Defense.webp", skillNum: "Defense" },
    ]
};
