import { yiSangskillData } from "./SkillData/yiSang.js";
import { faustskillData } from "./SkillData/Faust.js";
import { donskillData } from "./SkillData/Don.js";
import { ryoshuskillData } from "./SkillData/Ryoshu.js";
import { meursaultskillData } from "./SkillData/Meursault.js";
import { hongluskillData } from "./SkillData/HongLu.js";
import { heathcliffskillData } from "./SkillData/Heathcliff.js";
import { ishmaelskillData } from "./SkillData/Ishmael.js";
import { rodionskillData } from "./SkillData/Rodion.js";
import { sinclairskillData } from "./SkillData/Sinclair.js";
import { outisskillData } from "./SkillData/Outis.js";
import { gregorskillData } from "./SkillData/Gregor.js";
export const yiSangIDs = [
    { sinner: "Yi Sang", idName: "LCB Sinner", image: "IDs/YiSang/LCB_Yi_Sang.webp", portrait: "IDs/YiSang/Portraits/LCB_Yi_Sang.jpg",
        quote: "I am Yi Sang. My name is all I have to say.", skills: yiSangskillData.LCBYiSang, voiceline: "IDs/YiSang/Voicelines/LCB_YiSang.wav", rarity: "Ø" },
    { sinner: "Yi Sang", idName: "Dieci Assoc. South Section 4", image: "IDs/YiSang/DS4_YiSang.webp", portrait: "IDs/YiSang/Portraits/DS4_YiSang.jpg",
        quote: "Is that so... Then I must not grow complacent with my studies. I shall persevere.", skills: yiSangskillData.DieciYiSang, voiceline: "IDs/YiSang/Voicelines/Dieci_YiSang.ogg", rarity: "ØØ" },
    { sinner: "Yi Sang", idName: "LCE E.G.O::Lantern", image: "IDs/YiSang/LCE_YiSang.webp", portrait: "IDs/YiSang/Portraits/LCE_YiSang.jpg",
        quote: "Ah, may I ask you to continue this pretense that you are yet to spy myy location? The escpaed Abnormality will soon find interest in me and approach... and I shall smite it with a single swing of this hammer.",
        skills: yiSangskillData.LCEYiSang, voiceline: "IDs/YiSang/Voicelines/LCE_YiSang.wav", rarity: "ØØ" },
    { sinner: "Yi Sang", idName: "Molar Office Fixer", image: "IDs/YiSang/MOF_YiSang.webp", portrait: "IDs/YiSang/Portraits/MOF_YiSang.jpg",
        quote: "Hm. This is quite the responsibility. I shall try my best to live up to your expectations.", skills: yiSangskillData.MolarYiSang, voiceline: "IDs/YiSang/Voicelines/Molar_YiSang.wav", rarity: "ØØ" },
    { sinner: "Yi Sang", idName: "The Pequod First Mate", image: "IDs/YiSang/TPF_YiSang.webp", portrait: "IDs/YiSang/Portraits/TPF_YiSang.jpg",
        quote: "Thus I must step up to the occasion, then...! Very well. Wield the harpoon I shall!", skills: yiSangskillData.PequodYiSang, voiceline: "IDs/YiSang/Voicelines/Pequod.ogg", rarity: "ØØ" },
    { sinner: "Yi Sang", idName: "Seven Assoc. South Section 6", image: "IDs/YiSang/SA6_YiSang.webp", portrait: "IDs/YiSang/Portraits/SA6_YiSang.jpg",
        quote: "It was as I expected.", skills: yiSangskillData.SevenYiSang, voiceline: "IDs/YiSang/Voicelines/Seven.wav", rarity: "ØØ" },
    { sinner: "Yi Sang", idName: "Blade Lineage Salsu", image: "IDs/YiSang/BL_YiSang.webp", portrait: "IDs/YiSang/Portraits/BL_YiSang.jpg",
        quote: "I shall stay by your side until my sword breaks.", skills: yiSangskillData.BladeYiSang, voiceline: "IDs/YiSang/Voicelines/Blade.wav", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "Effloresced E.G.O::SpiceBush", image: "IDs/YiSang/Spicebush_YiSang.webp", portrait: "IDs/YiSang/Portraits/Spicebush_YiSang.jpg",
        quote: "Now... Behold. These flowers are in full glory. Once all these flowers have been stained red... that shall be when 'I' bloom as well.",
        skills: yiSangskillData.EfflorescedYiSang, voiceline: "IDs/YiSang/Voicelines/Effloresced.wav", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "Heishou Pack - Wu Branch Adept Yi Sang", image: "IDs/YiSang/Heishou_YiSang.webp", portrait: "IDs/YiSang/Portraits/Heishou_YiSang.jpg",
        quote: "Ride, beating of hooves. Rise, grains of sang. Ring, cries of war. Rest, for your flight shall meet a dead end. Thus I felled the rogue rebel as His Majesty has commanded- then, Hongyuan, march on... without fear.",
        skills: yiSangskillData.HeishouYiSang, voiceline: "IDs/YiSang/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "The House of Spiders: The Index Nursefather", image: "IDs/YiSang/Index_YiSang.webp", portrait: "IDs/YiSang/Portraits/Index_YiSang.jpg",
        quote: `*beep* "Lance the heart and hang upside-down." *beep* "Peck away with a sword and gnaw." *beep* ... There is no cause for you to harbor resentment. Your death... must itself have been ordainged by the Prescript's pleasure.`,
        skills: yiSangskillData.IndexYiSang, voiceline: "IDs/YiSang/Voicelines/Index.wav", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "Liu Assoc. South Section 3", image: "IDs/YiSang/LS3_YiSang.webp", portrait: "IDs/YiSang/Portraits/LS3_YiSang.jpg",
        quote: "It is unpleasant business to have noise compounded with bustle; I shall bring calm and silence to my presence.",
        skills: yiSangskillData.LiuYiSang, voiceline: "IDs/YiSang/Voicelines/Liu.ogg", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "Lobotomy E.G.O::Solemn Lament", image: "IDs/YiSang/Solemn_YiSang.webp", portrait: "IDs/YiSang/Portraits/Solemn_YiSang.jpg",
        quote: "It is a heavy gift that I shoulder; a twain of wayward souls in each of my palms, fingers held ever-closer. Where lies out destination now?",
        skills: yiSangskillData.LobotomyYiSang, voiceline: "IDs/YiSang/Voicelines/Lobotomy.ogg", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "N Corp. E.G.O::Fell Bullet", image: "IDs/YiSang/Fell_YiSang.webp", portrait: "IDs/YiSang/Portraits/Fell_YiSang.jpg",
        quote: "Are we to embark on a mission? How many shall accompany us? Mm. I ask, for I must count my bullets ere it begins.",
        skills: yiSangskillData.NCorpYiSang, voiceline: "IDs/YiSang/Voicelines/NCorp.wav", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "The Ring Pointillist Student", image: "IDs/YiSang/Ring_YiSang.webp", portrait: "IDs/YiSang/Portraits/Ring_YiSang.jpg",
        quote: "Aha, you wished to watch as I evaluated them? Come hither; allow me to guide you to those that are worth viewing.",
        skills: yiSangskillData.RingYiSang, voiceline: "IDs/YiSang/Voicelines/Ring.ogg", rarity: "ØØØ" },
    { sinner: "Yi Sang", idName: "W Corp. L3 Cleanup Agent", image: "IDs/YiSang/WCorp_YiSang.webp", portrait: "IDs/YiSang/Portraits/WCorp_YiSang.jpg",
        quote: "You insinuate that I am rather capable? ... Very well. ...I would appreciate it if you would take note of my teaching abilities also.",
        skills: yiSangskillData.WCorpYiSang, voiceline: "IDs/YiSang/Voicelines/WCorp.ogg", rarity: "ØØØ" }
    // { sinner: "Yi Sang", idName: "", image: "IDs/YiSang/_YiSang.webp", portrait: "IDs/YiSang/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const faustIDs = [
    { sinner: "Faust", idName: "LCB Sinner", image: "IDs/Faust/LCB_Faust.webp", portrait: "IDs/Faust/Portraits/LCB_Faust.jpg",
        quote: "It's Faust. A genius with whom you're lucky to cross paths even once in your life.", skills: faustskillData.LCBFaust, voiceline: "IDs/Faust/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Faust", idName: "Lobotomy Corp. Remnant", image: "IDs/Faust/LCR_Faust.webp", portrait: "IDs/Faust/Portraits/LCR_Faust.jpg",
        quote: "I suppose I'll put forth some effort one more time.", skills: faustskillData.LobotomyFaust, voiceline: "IDs/Faust/Voicelines/Lobotomy.wav", rarity: "ØØ" },
    { sinner: "Faust", idName: "W Corp. L2 Cleanup Agent", image: "IDs/Faust/WCorp_Faust.webp", portrait: "IDs/Faust/Portraits/WCorp_Faust.jpg",
        quote: "I'm starting to get a good grasp of this place.", skills: faustskillData.WCorpFaust, voiceline: "IDs/Faust/Voicelines/WCorp.wav", rarity: "ØØ" },
    { sinner: "Faust", idName: "Wuthering Heights Butler", image: "IDs/Faust/WH_Faust.webp", portrait: "IDs/Faust/Portraits/WH_Faust.jpg",
        quote: "... Come this way, dear guests. For any and all uninvited guests, though we sincerely apologize for this impudence, we must ask you to immediately vacate the premises.",
        skills: faustskillData.ButlerFaust, voiceline: "IDs/Faust/Voicelines/Butler.ogg", rarity: "ØØ" },
    { sinner: "Faust", idName: "Zwei Assoc. South Section 4", image: "IDs/Faust/ZS4_Faust.webp", portrait: "IDs/Faust/Portraits/ZS4_Faust.jpg",
        quote: "Yes, indeed. It is only natural that greater responsibilities are assigned to finer agents. I look forward to working with you.",
        skills: faustskillData.ZweiFaust, voiceline: "IDs/Faust/Voicelines/Zwei.ogg", rarity: "ØØ" },
    { sinner: "Faust", idName: "Blade Lineage Salsu", image: "IDs/Faust/BL_Faust.webp", portrait: "IDs/Faust/Portraits/BL_Faust.jpg",
        quote: "This is a good night to engage in a dance of blades. Particularly exquisite are the flowers blossoming from the tip of a moon-dipped blade. Why not go and appreciate the petals?",
        skills: faustskillData.BladeFaust, voiceline: "IDs/Faust/Voicelines/Blade.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "Dawn Office Fixer", image: "IDs/Faust/Dawn.png", portrait: "IDs/Faust/Portraits/Dawn.png",
        quote: "Let us cut the conversation short, shall we? Herr Gregor, Sinclair... Let us proceed at once.", skills: faustskillData.DawnFaust, voiceline: "IDs/Faust/Voicelines/Dawn.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "Heishou Pack - Mao Branch Adept", image: "IDs/Faust/Heishou_Faust.webp", portrait: "IDs/Faust/Portraits/Heishou_Faust.jpg",
        quote: "Your will is understood; that vision of righteousness shall swiftly be realized.", skills: faustskillData.HeishouFaust, voiceline: "IDs/Faust/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "The House of Spiders: The Ring Apprentice", image: "IDs/Faust/Ring_Faust.webp", portrait: "IDs/Faust/Portraits/Ring_Faust.jpg",
        quote: "Focus your ears and listen. Listen to Fascia's heartbeat... this pulsating sound of life!", skills: faustskillData.RingFaust, voiceline: "IDs/Faust/Voicelines/Ring.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "The Index Proselyte:【Paper Slip】", image: "IDs/Faust/Index_Faust.webp", portrait: "IDs/Faust/Portraits/Index_Faust.jpg",
        quote: `A new Prescript has arrived: "Behead seven dwellers of the Backstreets who resist when a blade touches their throat." The tally aligns—seven of you stand before me. I shall commence.`,
        skills: faustskillData.IndexFaust, voiceline: "IDs/Faust/Voicelines/Index.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "LCE E.G.O::Ardor Blossom Star", image: "IDs/Faust/Ardor_Faust.webp", portrait: "IDs/Faust/Portraits/Ardor_Faust.jpg",
        quote: "Those enticed by the lapping flames will be incinerated without a trace.", skills: faustskillData.LCEFaust, voiceline: "IDs/Faust/Voicelines/LCE.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "Lobotomy E.G.O::Regret", image: "IDs/Faust/Regret_Faust.webp", portrait: "IDs/Faust/Portraits/Regret_Faust.jpg",
        quote: "Control Team Captain, Agent Faust. Commencing suppression of the Green Dawn Ordeal as per the Manager's orders.",
        skills: faustskillData.RegretFaust, voiceline: "IDs/Faust/Voicelines/Regret.ogg", rarity: "ØØØ" },
    { sinner: "Faust", idName: "MultiCrack Office Rep", image: "IDs/Faust/MCR_Faust.webp", portrait: "IDs/Faust/Portraits/MCR_Faust.jpg",
        quote: "The contract target has been taken care of. The meticulous preparation for this contract expedition has certainly borne fruit.",
        skills: faustskillData.MultiCrackFaust, voiceline: "IDs/Faust/Voicelines/MultiCrack.ogg", rarity: "ØØØ" },
    { sinner: "Faust", idName: "The One Who Grips", image: "IDs/Faust/Grips_Faust.webp", portrait: "IDs/Faust/Portraits/Grips_Faust.jpg",
        quote: "Higher… Still higher! Let me advance… toward a purer body… Huhu!", skills: faustskillData.NCorpFaust, voiceline: "IDs/Faust/Voicelines/NCorp.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "Seven Assoc. South Section 4", image: "IDs/Faust/SA4_Faust.webp", portrait: "IDs/Faust/Portraits/SA4_Faust.jpg",
        quote: "Yes, of course. You may call upon me at any time should the need arise. Unless it's tea time, that is.", skills: faustskillData.SevenFaust, voiceline: "IDs/Faust/Voicelines/Seven.wav", rarity: "ØØØ" },
    { sinner: "Faust", idName: "Shi Assoc. East Section 3", image: "IDs/Faust/SE3_Faust.webp", portrait: "IDs/Faust/Portraits/SE3_Faust.jpg",
        quote: "Nock the arrow, pull, loose—it punches through the target, felling it. It is simple, manual labor with very little chance of error.",
        skills: faustskillData.ShiFaust, voiceline: "IDs/Faust/Voicelines/Shi.wav", rarity: "ØØØ" }
    // { sinner: "Faust", idName: "", image: "IDs/Faust/_Faust.webp", portrait: "IDs/Faust/Portraits/", quote: "", skills: faustskillData. , voiceline: "", rarity: "ØØØ" } For future use
];
export const donIDs = [
    { sinner: "Don Quixote", idName: "LCB Sinner", image: "IDs/Don/LCB_Don.webp", portrait: "IDs/Don/Portraits/LCB_Don.jpg",
        quote: "Hath my time come? I am Don Quixote!", skills: donskillData.LCBDon, voiceline: "IDs/Don/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Don Quixote", idName: "Blade Lineage Salsu", image: "IDs/Don/BL_Don.webp", portrait: "IDs/Don/Portraits/BL_Don.jpg",
        quote: "Ah, 'twas naught but the noise outside. Wouldst thou mind if I should go on a little stroll to investigate?",
        skills: donskillData.BladeDon, voiceline: "IDs/Don/Voicelines/Blade.ogg", rarity: "ØØ" },
    { sinner: "Don Quixote", idName: "Lobotomy E.G.O::Lantern", image: "IDs/Don/Lantern_Don.webp", portrait: "IDs/Don/Portraits/Lantern_Don.jpg",
        quote: "I cannot contain my joy Manager Esquire!!! Prithee, bring forth more villains for me to thrash!",
        skills: donskillData.LanternDon, voiceline: "IDs/Don/Voicelines/Lantern.ogg", rarity: "ØØ" },
    { sinner: "Don Quixote", idName: "N Corp. Mittelhammer", image: "IDs/Don/NCorp_Don.webp", portrait: "IDs/Don/Portraits/NCorp_Don.jpg",
        quote: "Keehee! Ahahahah! Upstanding...! Purging.", skills: donskillData.NCorpDon, voiceline: "IDs/Don/Voicelines/NCorp.wav", rarity: "ØØ" },
    { sinner: "Don Quixote", idName: "Shi Assoc. South Section 5 Director", image: "IDs/Don/SA5_Don.webp", portrait: "IDs/Don/Portraits/SA5_Don.jpg",
        quote: "I.. shall exert greater efforts! Watch me, Manager Esquire!", skills: donskillData.ShiDon, voiceline: "IDs/Don/Voicelines/Shi.wav", rarity: "ØØ" },
    { sinner: "Don Quixote", idName: "Cinq Assoc. East Section 3", image: "IDs/Don/CE3_Don.webp", portrait: "IDs/Don/Portraits/CE3_Don.jpg",
        quote: "Oof, apologies to thee. The gentleman there hath requested an 'emergency duel proxy' contract. I shall return in no time!",
        skills: donskillData.CinqEDon, voiceline: "IDs/Don/Voicelines/CinqE.wav", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "Cinq Assoc. South Section 5 Director", image: "IDs/Don/CS5_Don.webp", portrait: "IDs/Don/Portraits/CS5_Don.jpg",
        quote: "Aha! To be recognized is to be bestowed with honor! I thank thee!", skills: donskillData.CinqSDon, voiceline: "IDs/Don/Voicelines/CinqS.wav", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "Heishou Pack - Wei Branch", image: "IDs/Don/Heishou_Don.webp", portrait: "IDs/Don/Portraits/Heishou_Don.jpg",
        quote: "Turn back not, I say! There, forward ye charge! The pack of sheep shall break and shatter all that standeth before ye!",
        skills: donskillData.HeishouDon, voiceline: "IDs/Don/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "The Index Proxy - Effloresced E.G.O::Procuration", image: "IDs/Don/Index_Don.webp", portrait: "IDs/Don/Portraits/Index_Don.jpg",
        quote: `Th-they who wander hither without a spiral in their hearts… shall risk the dire displeasure of my master. Yea, nor would the Great Magicked Beeper, nor Rocinante, shall take kindly to such souls. Wouldst thou not agree?`,
        skills: donskillData.IndexDon, voiceline: "IDs/Don/Voicelines/Index.wav", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "Lobotomy E.G.O::In the Name of Love and Hate", image: "IDs/Don/Love_Don.webp", portrait: "IDs/Don/Portraits/Love_Don.jpg",
        quote: `Hark, one and all! Cease thy panicking, for I am here! Cast upon me any task thou seest fit: Abnormality containment breach suppression, containment unit management, insane employee suppression, anything shall do! Prithee, do summon me, as I shall doubtless be of assistance!`,
        skills: donskillData.QoHDon, voiceline: "IDs/Don/Voicelines/QoH.wav", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "The Manager of La Manchaland", image: "IDs/Don/Manager_Don.webp", portrait: "IDs/Don/Portraits/Manager_Don.jpg",
        quote: "Was it sweet, your hollow, juvenile dream? It is about time you awakened from it. Take responsibility for those you had once abandoned in the hands of others. Resent us, O Father. For we shall resent you in return.",
        skills: donskillData.ManagerDon, voiceline: "IDs/Don/Voicelines/Manager.ogg", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "The Middle Little Sister", image: "IDs/Don/Middle_Don.webp", portrait: "IDs/Don/Portraits/Middle_Don.jpg",
        quote: "I have been tasked by the Big Brother himself to carry out this quest for the Book of Vengeance! Haha, heigh-ho! I must live up to his expectations!",
        skills: donskillData.MiddleDon, voiceline: "IDs/Don/Voicelines/Middle.ogg", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "T Corp. Class 3 Collection Staff", image: "IDs/Don/TCorp_Don.webp", portrait: "IDs/Don/Portraits/TCorp_Don.jpg",
        quote: "Commencing Time Collections. Watch thy distance, lest thine own time be siphoned.", skills: donskillData.TCorpDon, voiceline: "IDs/Don/Voicelines/TCorp.ogg", rarity: "ØØØ" },
    { sinner: "Don Quixote", idName: "W Corp.L3 Cleanup Agent", image: "IDs/Don/WCorp_Don.webp", portrait: "IDs/Don/Portraits/WCorp_Don.jpg",
        quote: "Will I finally be given an important task?!", skills: donskillData.WCorpDon, voiceline: "IDs/Don/Voicelines/WCorp.wav", rarity: "ØØØ" }
    // { sinner: "Don Quixote", idName: "", image: "IDs/Don/_Don.webp", portrait: "IDs/Don/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const ryoshuIDs = [
    { sinner: "Ryōshū", idName: "LCB Sinner", image: "IDs/Ryoshu/LCB_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/LCB_Ryoshu.jpg",
        quote: "It's Ryōshū. Shūre's nice to meet ya. ...Pft.", skills: ryoshuskillData.LCBRyoshu, voiceline: "IDs/Ryoshu/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Ryōshū", idName: "District 20 Yurodivy Ryoshu", image: "IDs/Ryoshu/Yurodivy_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/Yurodivy_Ryoshu.jpg",
        quote: "Hmph, fine—record all you want. Just make sure to get all the blood splatters.", skills: ryoshuskillData.YurodivyRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Yurodivy.ogg", rarity: "ØØ" },
    { sinner: "Ryōshū", idName: "LCCB Assistant Manager", image: "IDs/Ryoshu/LCCB_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/LCCB_Ryoshu.jpg",
        quote: "Acknowledge. This is Ryōshū. Reporting total unit annihilation... Huh. The radio's also dead. Finally... I can let loose.",
        skills: ryoshuskillData.LCCBRyoshu, voiceline: "IDs/Ryoshu/Voicelines/LCCB.ogg", rarity: "ØØ" },
    { sinner: "Ryōshū", idName: "Liu Assoc. South Section 4", image: "IDs/Ryoshu/LS4_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/LS4_Ryoshu.jpg",
        quote: "Section Director… Thought she was a useless loudmouth, but she taught me this particularly useful skill. Heh, I could use this as a finisher.",
        skills: ryoshuskillData.LiuRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Liu.ogg", rarity: "ØØ" },
    { sinner: "Ryōshū", idName: "Seven Assoc. South Section 6", image: "IDs/Ryoshu/SA6_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/SA6_Ryoshu.jpg",
        quote: "Hmph, I knew you would.", skills: ryoshuskillData.SevenRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Seven.wav", rarity: "ØØ" },
    { sinner: "Ryōshū", idName: "Blade of the House of Spiders", image: "IDs/Ryoshu/HoS_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/HoS_Ryoshu.jpg",
        quote: "I will cut down every one of you across every world... Scrape every last trace of you out of reality... And then, I alone will hold all that has been severed... It's nothing more than a return to a state of Arayashiki.",
        skills: ryoshuskillData.HoSRyoshu, voiceline: "IDs/Ryoshu/Voicelines/HoS.wav", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "Drifting Blade of Hongyuan", image: "IDs/Ryoshu/Hongyuan_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/Hongyuan_Ryoshu.jpg",
        quote: "I drift aimlessly with no lord to serve, yet still they insist on standing in my way… Hah. No doubt Daguanyuan knows it's the body in the grave that guides the tip of my spear.",
        skills: ryoshuskillData.HongyuanRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Hongyuan.wav", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "Edgar Family Chief Butler", image: "IDs/Ryoshu/Edgar_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/Edgar_Ryoshu.jpg",
        quote: "Very well. It's about time we put an end to this, Heathcliff. Because you're… my 'housekeeping chore' to take care of.",
        skills: ryoshuskillData.ButlerRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Butler.ogg", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "Heishou Pack - Mao Branch", image: "IDs/Ryoshu/Heishou_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/Heishou_Ryoshu.jpg",
        quote: "How does it feel, as the teeth of a beast you once trusted sink deep into your neck? Explain it slowly, and in detail. I won't rush.",
        skills: ryoshuskillData.HeishouRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "Kurokumo Clan Wakashu", image: "IDs/Ryoshu/Kurokumo_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/Kurokumo_Ryoshu.jpg",
        quote: "I'll show you the ultimate swordsmanship.", skills: ryoshuskillData.KurokumoRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Kurokumo.wav", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "Lobotomy E.G.O::Faint Aroma & Solitude", image: "IDs/Ryoshu/Faint_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/Faint_Ryoshu.jpg",
        quote: "If a single bolt won't pierce through it, then emptying the whole cylinder of this six-shooter gets the job done. *puff* See that? That's how you use an E.G.O weapon, amateurs.",
        skills: ryoshuskillData.FASRyoshu, voiceline: "IDs/Ryoshu/Voicelines/FAS.wav", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "Lobotomy E.G.O::Red Eyes & Penitence", image: "IDs/Ryoshu/Red_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/Red_Ryoshu.jpg",
        quote: "Ever seen an E.G.O this well-tamed? This multi-eyed one just feels so natural in my hand.", skills: ryoshuskillData.REPRyoshu, voiceline: "IDs/Ryoshu/Voicelines/REP.ogg", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "N Corp. E.G.O::Contempy, Awe", image: "IDs/Ryoshu/NCorp_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/NCorp_Ryoshu.jpg",
        quote: "You squalid thing. Without my touch, that abominable form is unable to change, unable to be hidden. So… scatter.", skills: ryoshuskillData.NCorpRyoshu, voiceline: "IDs/Ryoshu/Voicelines/NCorp.wav", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "R.B. Chef Cuisine", image: "IDs/Ryoshu/RB_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/RB_Ryoshu.jpg",
        quote: "Finally, I'm joining the Eight— This isn't about that? Tsk, not that interested then.", skills: ryoshuskillData.ChefRyoshu, voiceline: "IDs/Ryoshu/Voicelines/Chef.wav", rarity: "ØØØ" },
    { sinner: "Ryōshū", idName: "W Corp. L3 Cleanup Agent", image: "IDs/Ryoshu/WCorp_Ryoshu.webp", portrait: "IDs/Ryoshu/Portraits/WCorp_Ryoshu.jpg",
        quote: "Hmph. So you acknowledge my abilities. Then assign me to proper fieldwork, not babysitting.", skills: ryoshuskillData.WCorpRyoshu, voiceline: "IDs/Ryoshu/Voicelines/WCorp.wav", rarity: "ØØØ" }
    // { sinner: "Ryōshū", idName: "", image: "IDs/Ryoshu/_Ryoshu.webp", portrait: "IDs/Ryoshу/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const meursaultIDs = [
    { sinner: "Meursault", idName: "LCB Sinner", image: "IDs/Meursault/LCB_Meursault.webp", portrait: "IDs/Meursault/Portraits/LCB_Meursault.jpg",
        quote: "Meursault. Please refer to me as such, Manager.", skills: meursaultskillData.LCBMeursault, voiceline: "IDs/Meursault/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Meursault", idName: "Dead Rabbits Boss", image: "IDs/Meursault/Dead_Meursault.webp", portrait: "IDs/Meursault/Portraits/Dead_Meursault.jpg",
        quote: "We will soon have to make time. Quite opportune that there are other gangs roaming our streets. I see this as a perfect opportunity to make some extra time.",
        skills: meursaultskillData.DeadMeursault, voiceline: "IDs/Meursault/Voicelines/Dead.ogg", rarity: "ØØ" },
    { sinner: "Meursault", idName: "Liu Assoc, South Section 6", image: "IDs/Meursault/Liu_Meursault.webp", portrait: "IDs/Meursault/Portraits/Liu_Meursault.jpg",
        quote: "I will strive to become a keener flame.", skills: meursaultskillData.LiuMeursault, voiceline: "IDs/Meursault/Voicelines/Liu.wav", rarity: "ØØ" },
    { sinner: "Meursault", idName: "The Middle Little Brother", image: "IDs/Meursault/Middle_Meursault.webp", portrait: "IDs/Meursault/Portraits/Middle_Meursault.jpg",
        quote: "Has something happened to you? Please, come here and tell me what transpired, in full detail. I will add it to the Book of Vengeance so that this offense may be avenged.",
        skills: meursaultskillData.MiddleMeursault, voiceline: "IDs/Meursault/Voicelines/Middle.ogg", rarity: "ØØ" },
    { sinner: "Meursault", idName: "Rosespanner Workshop Fixer", image: "IDs/Meursault/Rosespanner_Meursault.webp", portrait: "IDs/Meursault/Portraits/Rosespanner_Meursault.jpg",
        quote: "Hm. You're giving me a raise. Entendu. Pardon me then, as I have tasks to take care of.", skills: meursaultskillData.RosespannerMeursault, voiceline: "IDs/Meursault/Voicelines/Rosespanner.wav", rarity: "ØØ" },
    { sinner: "Meursault", idName: "Blade Lineage Mentor", image: "IDs/Meursault/BL_Meursault.webp", portrait: "IDs/Meursault/Portraits/BL_Meursault.jpg",
        quote: "No matter how many assassins they send, they are nothing before me but the placement of a single stone in a game of baduk. My play has yet to flourish... will you respond nevertheless?",
        skills: meursaultskillData.BladeMeursault, voiceline: "IDs/Meursault/Voicelines/BL.ogg", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "Cinq Assoc. West Section 3", image: "IDs/Meursault/Cinq_Meursault.webp", portrait: "IDs/Meursault/Portraits/Cinq_Meursault.jpg",
        quote: "A moment, please. You will now observe a demonstration of a duel; the interview may resume afterward.",
        skills: meursaultskillData.CinqMeursault, voiceline: "IDs/Meursault/Voicelines/Cinq.ogg", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "Dieci Assoc. South Section 4", image: "IDs/Meursault/Dieci_Meursault.webp", portrait: "IDs/Meursault/Portraits/Dieci_Meursault.jpg",
        quote: "Thus from this brilliant fabric radiates the weight of layers upon layers of knowledge; now, my fists wreathed in its full weight, shall smite you down.",
        skills: meursaultskillData.DieciMeursault, voiceline: "IDs/Meursault/Voicelines/Dieci.ogg", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "Lobotomy E.G.O::Hornet 【Alteration】 ", image: "IDs/Meursault/Hornet_Meursault.webp", portrait: "IDs/Meursault/Portraits/Hornet_Meursault.jpg",
        quote: `Ordeal "Food Chain" identified. Commencing suppression and the requested field experimentation. Agents mustn't take offensive maneuvers even should the Captain be swallowed by an Ordeal. That would be all.`,
        skills: meursaultskillData.HornetMeursault, voiceline: "IDs/Meursault/Voicelines/Hornet.wav", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "N Corp. Großhammer", image: "IDs/Meursault/NCorp_Meursault.webp", portrait: "IDs/Meursault/Portraits/NCorp_Meursault.jpg",
        quote: "Though I believe myself to be ever too puny to deserve such recognition, I will accept if you insist.", skills: meursaultskillData.NCorpMeursault, voiceline: "IDs/Meursault/Voicelines/NCorp.wav", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "The Prince of La Manchaland", image: "IDs/Meursault/Prince_Meursault.webp", portrait: "IDs/Meursault/Portraits/Prince_Meursault.jpg",
        quote: "The Parade commences. Open the palace gates and let the soldiers take the vanguard in this procession. This is the endlessly, eternally blessed Carnival… So, do enjoy yourselves.",
        skills: meursaultskillData.PrinceMeursault, voiceline: "IDs/Meursault/Voicelines/Prince.wav", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "R Corp. 4th Pack Rhino Meursault", image: "IDs/Meursault/RCorp_Meursault.webp", portrait: "IDs/Meursault/Portraits/RCorp_Meursault.jpg",
        quote: "Understood. I will bring you results that are as good as your support.", skills: meursaultskillData.RCorpMeursault, voiceline: "IDs/Meursault/Voicelines/RCorp.wav", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "The Ring Fauvist Student", image: "IDs/Meursault/Ring_Meursault.webp", portrait: "IDs/Meursault/Portraits/Ring_Meursault.jpg",
        quote: "Hm. Loose claws: addressed. The excitement of the subject about to grip the prey in its claws: ... clearly communicated. This particular iteration is now worthy of submission for evaluation. ... In that case, now would be the opportune time to collect new material for my next piece.",
        skills: meursaultskillData.RingMeursault, voiceline: "IDs/Meursault/Voicelines/Ring.wav", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "The Thumb East Capo IIII", image: "IDs/Meursault/Thumb_Meursault.webp", portrait: "IDs/Meursault/Portraits/Thumb_Meursault.jpg",
        quote: "The fact that the name of Tiantui Star's blade must remain hidden is a shame, indeed… but here, that want is fulfilled by another—that I may roar like a winged tiger. This sates me.",
        skills: meursaultskillData.ThumbMeursault, voiceline: "IDs/Meursault/Voicelines/Thumb.wav", rarity: "ØØØ" },
    { sinner: "Meursault", idName: "W Corp. L3 Cleanup Agent", image: "IDs/Meursault/WCorp_Meursault.webp", portrait: "IDs/Meursault/Portraits/WCorp_Meursault.jpg",
        quote: "Promotions... That, I am used to.", skills: meursaultskillData.WCorpMeursault, voiceline: "IDs/Meursault/Voicelines/WCorp.wav", rarity: "ØØØ" }
    // { sinner: "Meursault", idName: "", image: "IDs/Meursault/_Meursault.webp", portrait: "IDs/Meursault/Portraits/", quote: "",voiceline: "", rarity: "ØØØ" } For future use
];
export const hongLuIDs = [
    { sinner: "Hong Lu", idName: "LCB Sinner", image: "IDs/HongLu/LCB_HongLu.webp", portrait: "IDs/HongLu/Portraits/LCB_HongLu.jpg",
        quote: "My name's Hong Lu. I hope we can get along well.", skills: hongluskillData.LCBHongLu, voiceline: "IDs/HongLu/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Hong Lu", idName: "Fanghunt Office Fixer", image: "IDs/HongLu/Fanghunt_HongLu.webp", portrait: "IDs/HongLu/Portraits/Fanghunt_HongLu.jpg",
        quote: "Ha ha… How does it feel, getting hunted down by your prey?", skills: hongluskillData.FanghuntHongLu, voiceline: "IDs/HongLu/Voicelines/Fanghunt.ogg", rarity: "ØØ" },
    { sinner: "Hong Lu", idName: "Hook Office Fixer", image: "IDs/HongLu/Hook_HongLu.webp", portrait: "IDs/HongLu/Portraits/Hook_HongLu.jpg",
        quote: "I agree, I did good work~ Just bring me some more, and I'll show you what I'm really made of. You will, right?", skills: hongluskillData.HookHongLu, voiceline: "IDs/HongLu/Voicelines/Hook.ogg", rarity: "ØØ" },
    { sinner: "Hong Lu", idName: "Kurokumo Clan Wakashu", image: "IDs/HongLu/Kurokumo_HongLu.webp", portrait: "IDs/HongLu/Portraits/Kurokumo_HongLu.jpg",
        quote: "Thank you. Is there anything else you'd like me to fell?", skills: hongluskillData.KurokumoHongLu, voiceline: "IDs/HongLu/Voicelines/Kurokumo.wav", rarity: "ØØ" },
    { sinner: "Hong Lu", idName: "Liu Assoc, South Section 5", image: "IDs/HongLu/Liu_HongLu.webp", portrait: "IDs/HongLu/Portraits/Liu_HongLu.jpg",
        quote: "I see~ I was starting to wonder when you'd bring this up~", skills: hongluskillData.LiuHongLu, voiceline: "IDs/HongLu/Voicelines/Liu.wav", rarity: "ØØ" },
    { sinner: "Hong Lu", idName: "W Corp. L2 Cleanup Agent", image: "IDs/HongLu/WCorp_HongLu.webp", portrait: "IDs/HongLu/Portraits/WCorp_HongLu.jpg",
        quote: "Oh, is this a new lesson? I hope it's about something new for once~", skills: hongluskillData.WCorpHongLu, voiceline: "IDs/HongLu/Voicelines/WCorp.wav", rarity: "ØØ" },
    { sinner: "Hong Lu", idName: "Cinq Assoc. East Section 3", image: "IDs/HongLu/Cinq_HongLu.webp", portrait: "IDs/HongLu/Portraits/Cinq_HongLu.jpg",
        quote: "Okay. Now, the Cinq will be taking over this duel. Hm… Why don't you yield? You might want to decide soon, because you're this close to catching fire, from the collar up.",
        skills: hongluskillData.CinqHongLu, voiceline: "IDs/HongLu/Voicelines/Cinq.wav", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "Dieci Assoc. South Section 4", image: "IDs/HongLu/Dieci_HongLu.webp", portrait: "IDs/HongLu/Portraits/Dieci_HongLu.jpg",
        quote: "Good thinking. Let my key be the guide to your enlightenment.", skills: hongluskillData.DieciHongLu, voiceline: "IDs/HongLu/Voicelines/Dieci.ogg", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "District 20 Yurodivy", image: "IDs/HongLu/Yurodivy_HongLu.webp", portrait: "IDs/HongLu/Portraits/Yurodivy_HongLu.jpg",
        quote: "Okay, let's think. How would I do this, if I was the killer? I just have to slowly think it through, and… … Hehe, I suppose I'll find the truth sooner or later, hm?",
        skills: hongluskillData.YurodivyHongLu, voiceline: "IDs/HongLu/Voicelines/Yurodivy.ogg", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "Full-Stop Office Rep", image: "IDs/HongLu/FullStop_HongLu.webp", portrait: "IDs/HongLu/Portraits/FullStop_HongLu.jpg",
        quote: "Three shots to the chest, and… doesn't look like I'll even need to shoot them in the head for good measure.", skills: hongluskillData.FullStopHongLu, voiceline: "IDs/HongLu/Voicelines/FullStop.wav", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "The House of Spiders: The Ring Nursefather", image: "IDs/HongLu/Ring_HongLu.webp", portrait: "IDs/HongLu/Portraits/Ring_HongLu.jpg",
        quote: "Allow me to play the curator for our guests—from kitsch to avant-garde, delving deep into each trend of art movement.",
        skills: hongluskillData.RingHongLu, voiceline: "IDs/HongLu/Voicelines/Ring.wav", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "K Corp. Class 3 Excision Staff", image: "IDs/HongLu/KCorp_HongLu.webp", portrait: "IDs/HongLu/Portraits/KCorp_HongLu.jpg",
        quote: "Is it a... deployment order? You'll be calling me more often in the future? That's wonderful~ I've been terribly bored.", skills: hongluskillData.KCorpHongLu, voiceline: "IDs/HongLu/Voicelines/KCorp.wav", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "The Lord of Hongyuan", image: "IDs/HongLu/Lord_HongLu.webp", portrait: "IDs/HongLu/Portraits/Lord_HongLu.jpg",
        quote: "Adepts of each Branch shall heed me: your Lord finds this present circumstance… utterly vexing. Educate them. Teach them what conclusion awaits those who dare wield the blade of rebellion to recalcitrate against their Lord.",
        skills: hongluskillData.LordHongLu, voiceline: "IDs/HongLu/Voicelines/Lord.wav", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "R Corp. 4th Pack Reindeer", image: "IDs/HongLu/RCorp_HongLu.webp", portrait: "IDs/HongLu/Portraits/RCorp_HongLu.jpg",
        quote: "Don't be anxious… don't be… I have to empty my thoughts to endure this— Agh! Get lost!", skills: hongluskillData.RCorpHongLu, voiceline: "IDs/HongLu/Voicelines/RCorp.wav", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "S Corp. Ch'unokkun", image: "IDs/HongLu/SCorp_HongLu.webp", portrait: "IDs/HongLu/Portraits/SCorp_HongLu.jpg",
        quote: "All right, be a nice Nobi and come on out, so I can tie you up like the convict that you are! Let's not keep my Scarlet Bonds waiting, okay?",
        skills: hongluskillData.SCorpHongLu, voiceline: "IDs/HongLu/Voicelines/SCorp.wav", rarity: "ØØØ" },
    { sinner: "Hong Lu", idName: "Tingtang Gang Gangleader", image: "IDs/HongLu/Tingtang_HongLu.webp", portrait: "IDs/HongLu/Portraits/Tingtang_HongLu.jpg",
        quote: "Oh, you're flattering me~ I won't say no to it, though~", skills: hongluskillData.TingtangHongLu, voiceline: "IDs/HongLu/Voicelines/Tingtang.wav", rarity: "ØØØ" }
    // { sinner: "Hong Lu", idName: "", image: "IDs/HongLu/_HongLu.webp", portrait: "IDs/HongLu/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const heathcliffIDs = [
    { sinner: "Heathcliff", idName: "LCB Sinner", image: "IDs/Heathcliff/LCB_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/LCB_Heathcliff.jpg",
        quote: "Name's Heathcliff. Clobbering people is my specialty. 'Course, only when I fancy it.", skills: heathcliffskillData.LCBHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Heathcliff", idName: "MultiCrack Office Fixer", image: "IDs/Heathcliff/MultiCrack_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/MultiCrack_Heathcliff.jpg",
        quote: "Oi, hey… This one's dead! Really, did you seriously kick the bucket from getting a few holes punctured on your torso?", skills: heathcliffskillData.MultiCrackHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/MultiCrack.ogg", rarity: "ØØ" },
    { sinner: "Heathcliff", idName: "N Corp. Kleinhammer", image: "IDs/Heathcliff/NCorp_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/NCorp_Heathcliff.jpg",
        quote: "Me…? No, don’t think I deserve to get all this… Not like I can refuse if you mean it.", skills: heathcliffskillData.NCorpHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/NCorp.wav", rarity: "ØØ" },
    { sinner: "Heathcliff", idName: "Seven Assoc. South Section 4", image: "IDs/Heathcliff/Seven_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Seven_Heathcliff.jpg",
        quote: "Ah. Uh—huh. Hold that thought. I'm starting to connect the dots. ...Ahh, so that's how that happened... Right. We'll chat later. Uh—huh, cheers.",
        skills: heathcliffskillData.SevenHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Seven.wav", rarity: "ØØ" },
    { sinner: "Heathcliff", idName: "Shi Assoc. South Section 5", image: "IDs/Heathcliff/Shi_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Shi_Heathcliff.jpg",
        quote: "I can keep on butchering 'em 'til you tell me to stop!", skills: heathcliffskillData.ShiHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Shi.wav", rarity: "ØØ" },
    { sinner: "Heathcliff", idName: "Full-Stop Office Fixer", image: "IDs/Heathcliff/FullStop_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/FullStop_Heathcliff.jpg",
        quote: "Oh bugger, they saw us! Fall back! I'll return fire…!", skills: heathcliffskillData.FullStopHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/FullStop.wav", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "Heishou Pack - You Branch Adept", image: "IDs/Heathcliff/Heishou_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Heishou_Heathcliff.jpg",
        quote: "Learn to appreciate our silence in the morning, yeah? Roosters crow only when the lord holding our leash commands us to.",
        skills: heathcliffskillData.HeishouHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "The House of Spiders: The Thumb Apprentice", image: "IDs/Heathcliff/Thumb_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Thumb_Heathcliff.jpg",
        quote: "In one-on-one duels, my Palermitan Style has the advantage.", skills: heathcliffskillData.ThumbHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Thumb.wav", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "Kurokumo Clan Wakashu", image: "IDs/Heathcliff/Kurokumo_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Kurokumo_Heathcliff.jpg",
        quote: "Hooah…! Anyone else lookin' for a thrashing?", skills: heathcliffskillData.KurokumoHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Kurokumo.ogg", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "Lobotomy E.G.O::Sunshower", image: "IDs/Heathcliff/Sunshower_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Sunshower_Heathcliff.jpg",
        quote: "Go on and pretend to be nice all you want... I'll stay wary and suspicious of you until all technology is liberated.", skills: heathcliffskillData.SunshowerHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Sunshower.wav", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "The Middle Big Brother", image: "IDs/Heathcliff/Middle_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Middle_Heathcliff.jpg",
        quote: "Memories are important, so remember this before you cough up the last breath you ain't keeping. Name's Heathcliff, a Big Brother of the Middle... the name of the one what's gonna exterminate the whole bloody lot o' you bastards!",
        skills: heathcliffskillData.MiddleHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Middle.wav", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "The Pequod Harpooneer", image: "IDs/Heathcliff/Pequod_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Pequod_Heathcliff.jpg",
        quote: "It is time. Time to kill the Whale. To destroy the Whale-heart. Time to escape.", skills: heathcliffskillData.PequodHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Pequod.ogg", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "R Corp. 4th Pack Rabbit", image: "IDs/Heathcliff/RCorp_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/RCorp_Heathcliff.jpg",
        quote: "Alright, now that's what I like to see!", skills: heathcliffskillData.RCorpHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/RCorp.wav", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "W Corp. L4 Cleanup Agent - CCA", image: "IDs/Heathcliff/WCorp_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/WCorp_Heathcliff.jpg",
        quote: "Back off to the other compartment… This bastard's a stowaway.", skills: heathcliffskillData.WCorpHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/WCorp.wav", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "Wild Hunt", image: "IDs/Heathcliff/Wild_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Wild_Heathcliff.jpg",
        quote: "The dawn of the promised banquet, the day of the hunt rises. I can feel it even at the tip of my hair... that the destruction of Wuthering Heights is nigh.",
        skills: heathcliffskillData.WildHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Wild.ogg", rarity: "ØØØ" },
    { sinner: "Heathcliff", idName: "Öufi Assoc. South Section 3", image: "IDs/Heathcliff/Oufi_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/Oufi_Heathcliff.jpg",
        quote: "That was your final warning. Now, as obstruction of contract execution has been observed, I am compelled to… beat the shite out of you all!",
        skills: heathcliffskillData.OufiHeathcliff, voiceline: "IDs/Heathcliff/Voicelines/Oufi.ogg", rarity: "ØØØ" }
    // { sinner: "Heathcliff", idName: "", image: "IDs/Heathcliff/_Heathcliff.webp", portrait: "IDs/Heathcliff/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const ishmaelIDs = [
    { sinner: "Ishmael", idName: "LCB Sinner", image: "IDs/Ishmael/LCB_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/LCB_Ishmael.jpg",
        quote: "Call me Ishmael, if you please.", skills: ishmaelskillData.LCBIshmael, voiceline: "IDs/Ishmael/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Ishmael", idName: "Edgar Family Butler", image: "IDs/Ishmael/Edgar_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Edgar_Ishmael.jpg",
        quote: "I am a Butler in the employment of your household. What else could I possibly provide other than the utmost competence? I will clean up every fool who seeks to take advantage of your sickness.",
        skills: ishmaelskillData.ButlerIshmael, voiceline: "IDs/Ishmael/Voicelines/Butler.ogg", rarity: "ØØ" },
    { sinner: "Ishmael", idName: "LCCB Assistant Manager", image: "IDs/Ishmael/LCCB_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/LCCB_Ishmael.jpg",
        quote: "Ishmael speaking. Is there anything I can help you with?", skills: ishmaelskillData.LCCBIshmael, voiceline: "IDs/Ishmael/Voicelines/LCCB.wav", rarity: "ØØ" },
    { sinner: "Ishmael", idName: "Lobotomy E.G.O::Sloshing", image: "IDs/Ishmael/Sloshing_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Sloshing_Ishmael.jpg",
        quote: "Oh, joy... I get recognition for this nonsense... Not sure how I should feel about it.", skills: ishmaelskillData.SloshingIshmael, voiceline: "IDs/Ishmael/Voicelines/Sloshing.wav", rarity: "ØØ" },
    { sinner: "Ishmael", idName: "Shi Assoc. South Section 5", image: "IDs/Ishmael/Shi_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Shi_Ishmael.jpg",
        quote: "I'll repay the favor with my performance, now that it's more reliable and efficient.", skills: ishmaelskillData.ShiIshmael, voiceline: "IDs/Ishmael/Voicelines/Shi.wav", rarity: "ØØ" },
    { sinner: "Ishmael", idName: "Family Heirarch Candidate", image: "IDs/Ishmael/Family_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Family_Ishmael.jpg",
        quote: "Didn't even have the courtesy of showing up to my banquet, but now you're here… at my Nuanxiangwu. Itching for a chance to cut off my head, huh?",
        skills: ishmaelskillData.FamilyIshmael, voiceline: "IDs/Ishmael/Voicelines/Family.wav", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "The House of Spiders: The Middle Apprentice", image: "IDs/Ishmael/Middle_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Middle_Ishmael.jpg",
        quote: "Nahh, he folded way too quick. Was tryna see every single move he'd flexed about in interviews and video streams—dude looked exactly like that protagonist from City Fighter 3 and all… Ugh, I really should've gotten an autograph before I kicked his ass into the afterlife.",
        skills: ishmaelskillData.MiddleIshmael, voiceline: "IDs/Ishmael/Voicelines/Middle.wav", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "Jeong's Office Rep", image: "IDs/Ishmael/Jeong_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Jeong_Ishmael.jpg",
        quote: "Nope. The card's out in the open... there's no forfeiting once the die is cast. No matter how screwed you are.", skills: ishmaelskillData.JeongIshmael, voiceline: "IDs/Ishmael/Voicelines/Jeong.wav", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "Kurokumo Clan Captain", image: "IDs/Ishmael/Kurokumo_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Kurokumo_Ishmael.jpg",
        quote: "My name is Ishmael, thirty-fourth Captain of the Kurokumo Clan… And I accept your Showdown challenge.", skills: ishmaelskillData.KurokumoIshmael, voiceline: "IDs/Ishmael/Voicelines/Kurokumo.ogg", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "LCD OSIR Team", image: "IDs/Ishmael/LCD_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/LCD_Ishmael.jpg",
        quote: `The winds may wear me down, and the rains may weather me hollow, but the edge of my blade shall never dull. Therefore, I will take up my burden as I am bidden to carry myself. *exhale* LCD On-site Investigative Reasoning Team Ishmael—now commencing Distortion capture as directed.`,
        skills: ishmaelskillData.LCDIshmael, voiceline: "IDs/Ishmael/Voicelines/LCD.wav", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "Liu Assoc. South Section 4", image: "IDs/Ishmael/Liu_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Liu_Ishmael.jpg",
        quote: "...I see. I'll get busier, won't I. Well, I'll be training myself to prepare for it.", skills: ishmaelskillData.LiuIshmael, voiceline: "IDs/Ishmael/Voicelines/Liu.wav", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "Molar Boatworks Fixer", image: "IDs/Ishmael/Molar_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Molar_Ishmael.jpg",
        quote: "Hup... I made a few modifications to the crab driver. I might try using this one to get the big guy.", skills: ishmaelskillData.MolarIshmael, voiceline: "IDs/Ishmael/Voicelines/Molar.wav", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "The Pequod Captain", image: "IDs/Ishmael/Pequod_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Pequod_Ishmael.jpg",
        quote: "Thunder and lightning… Yes, the battle of our lifetimes will soon be upon us! We will hunt the Whale of all evils! Hahahahahaha!",
        skills: ishmaelskillData.PequodIshmael, voiceline: "IDs/Ishmael/Voicelines/Pequod.ogg", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "R Corp. 4th Pack Reindeer", image: "IDs/Ishmael/RCorp_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/RCorp_Ishmael.jpg",
        quote: "Hngh... Haah, I feel my power has grown more potent... But my headache's gotten worse, too...", skills: ishmaelskillData.RcorpIshmael, voiceline: "IDs/Ishmael/Voicelines/RCorp.wav", rarity: "ØØØ" },
    { sinner: "Ishmael", idName: "Zwei Assoc. West Section 3", image: "IDs/Ishmael/Zwei_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/Zwei_Ishmael.jpg",
        quote: "Don't worry. Not even a single arrow will get through as long as I stand between you and your enemies.", skills: ishmaelskillData.ZweiIshmael, voiceline: "IDs/Ishmael/Voicelines/Zwei.ogg", rarity: "ØØØ" }
    // { sinner: "Ishmael", idName: "", image: "IDs/Ishmael/_Ishmael.webp", portrait: "IDs/Ishmael/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const rodionIDs = [
    { sinner: "Rodion", idName: "LCB Sinner", image: "IDs/Rodion/LCB_Rodion.webp", portrait: "IDs/Rodion/Portraits/LCB_Rodion.jpg",
        quote: "Hiya~ I'm Rodya. I have a longer name, but that makes things look cold, so just stick with Rodya~", skills: rodionskillData.LCBRodion, voiceline: "IDs/Rodion/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Rodion", idName: "LCCB Assistant Manager", image: "IDs/Rodion/LCCB_Rodion.webp", portrait: "IDs/Rodion/Portraits/LCCB_Rodion.jpg",
        quote: "A promotion at last? What's on the table? A raise? Transfer to the After Team? ...Neither? Phooey.", skills: rodionskillData.LCCBRodion, voiceline: "IDs/Rodion/Voicelines/LCCB.wav", rarity: "ØØ" },
    { sinner: "Rodion", idName: "N Corp. Mittelhammer", image: "IDs/Rodion/NCorp_Rodion.webp", portrait: "IDs/Rodion/Portraits/NCorp_Rodion.jpg",
        quote: "I swear, I swear to you! I will return this favor… Fuhu!", skills: rodionskillData.NCorpRodion, voiceline: "IDs/Rodion/Voicelines/NCorp.wav", rarity: "ØØ" },
    { sinner: "Rodion", idName: "T Corp. Class 2 Collection Staff", image: "IDs/Rodion/TCorp_Rodion.webp", portrait: "IDs/Rodion/Portraits/TCorp_Rodion.jpg",
        quote: "It's pointless to resist. I'll always be one step ahead of you because I'm pulling time from the future.", skills: rodionskillData.TCorpRodion, voiceline: "IDs/Rodion/Voicelines/TCorp.ogg", rarity: "ØØ" },
    { sinner: "Rodion", idName: "Zwei Assoc. South Section 5", image: "IDs/Rodion/Zwei_Rodion.webp", portrait: "IDs/Rodion/Portraits/Zwei_Rodion.jpg",
        quote: "It's good to be recognized~ Hm... Though, I'd prefer better pay for the missions~", skills: rodionskillData.ZweiRodion, voiceline: "IDs/Rodion/Voicelines/Zwei.wav", rarity: "ØØ" },
    { sinner: "Rodion", idName: "Devyat' Assoc. North Section 3", image: "IDs/Rodion/Devyat_Rodion.webp", portrait: "IDs/Rodion/Portraits/Devyat_Rodion.jpg",
        quote: "Courier Trunk activation level 1… Alright, let's take care of this before it gets to 3!", skills: rodionskillData.DevyatRodion, voiceline: "IDs/Rodion/Voicelines/Devyat.ogg", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "Dieci Assoc. South Section 4", image: "IDs/Rodion/Dieci_Rodion.webp", portrait: "IDs/Rodion/Portraits/Dieci_Rodion.jpg",
        quote: "How'd it go again? With knowledge as my key... I shall continue to devote myself to the opening of the door.", skills: rodionskillData.DieciRodion, voiceline: "IDs/Rodion/Voicelines/Dieci.wav", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "Heishou Pack - Si Branch", image: "IDs/Rodion/Heishou_Rodion.webp", portrait: "IDs/Rodion/Portraits/Heishou_Rodion.jpg",
        quote: "Didya see that? Doubt ya did… A crooked snake whips faster than the speed of sound, you know.", skills: rodionskillData.HeishouRodion, voiceline: "IDs/Rodion/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "The House of Spiders: The Thumb Nursefather", image: "IDs/Rodion/Thumb_Rodion.webp", portrait: "IDs/Rodion/Portraits/Thumb_Rodion.jpg",
        quote: "Haha… Do you even have any idea who you forgot… what you threw away to get this far? From the first day her baby hands held a sword, all the way to the day she brought you here, I… You got any idea how I honed that Ticket of mine, day after day…? Ungrateful little bitch, how dare you forget my Ticket!",
        skills: rodionskillData.ThumbRodion, voiceline: "IDs/Rodion/Voicelines/Thumb.wav", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "Kurokumo Clan Wakashu", image: "IDs/Rodion/Kurokumo_Rodion.webp", portrait: "IDs/Rodion/Portraits/Kurokumo_Rodion.jpg",
        quote: "You aren't gonna make a difference by doing a street dweller like me extra favors. It's not like I'm here to stay... Still, I guess it's nice to get something.",
        skills: rodionskillData.KurokumoRodion, voiceline: "IDs/Rodion/Voicelines/Kurokumo.wav", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "Liu Assoc. South Section 4 Director", image: "IDs/Rodion/Liu_Rodion.webp", portrait: "IDs/Rodion/Portraits/Liu_Rodion.jpg",
        quote: "Focus on a singular point. A single, determined strike against a sole point could hurt just as much as a spear or a sword. Even if you stab 'em bare-handed.",
        skills: rodionskillData.LiuRodion, voiceline: "IDs/Rodion/Voicelines/Liu.ogg", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "Lobotomy E.G.O::The Sword Sharpened with Tears", image: "IDs/Rodion/KoD_Rodion.webp", portrait: "IDs/Rodion/Portraits/KoD_Rodion.jpg",
        quote: "I'm going to fight back with those tears and the constellations we extracted from you. It doesn't matter if I was your chosen one or not—I have to carry out the manager's orders.",
        skills: rodionskillData.KoDRodion, voiceline: "IDs/Rodion/Voicelines/KoD.wav", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "The Princess of La Manchaland", image: "IDs/Rodion/Princess_Rodion.webp", portrait: "IDs/Rodion/Portraits/Princess_Rodion.jpg",
        quote: "The Parade will be… different tonight. The real Carnival begins now.", skills: rodionskillData.PrincessRodion, voiceline: "IDs/Rodion/Voicelines/Princess.ogg", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "R Corp. 4th Pack Reindeer", image: "IDs/Rodion/RCorp_Rodion.webp", portrait: "IDs/Rodion/Portraits/RCorp_Rodion.jpg",
        quote: "… Yeah, Merry Christmas to us all. Let there be blessings or whatever to all the poor souls working the holy night away.", skills: rodionskillData.RCorpRodion, voiceline: "IDs/Rodion/Voicelines/RCorp.wav", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "The Ring Fauvist Docent", image: "IDs/Rodion/Ring_Rodion.webp", portrait: "IDs/Rodion/Portraits/Ring_Rodion.jpg",
        quote: "Hear that? That's the feral melody of bones, all taken from different creatures, finally locking together. There—just a few tendons tugged, and it all clicks right into place, clean and snug... Hey, wait up. Are ya not even gonna pretend to hear me out before making a break for it? Well, if you don't wanna... Guess I'll just have to carve it into your bones instead. That tends to leave an unforgettable impression.",
        skills: rodionskillData.RingRodion, voiceline: "IDs/Rodion/Voicelines/Ring.wav", rarity: "ØØØ" },
    { sinner: "Rodion", idName: "Rosespanner Workshop Rep", image: "IDs/Rodion/Rosespanner_Rodion.webp", portrait: "IDs/Rodion/Portraits/Rosespanner_Rodion.jpg",
        quote: "Hm~? I'm already the rep, I don't see how I can get to a higher position~ Just get us more work instead!", skills: rodionskillData.RosespannerRodion, voiceline: "IDs/Rodion/Voicelines/Rosespanner.wav", rarity: "ØØØ" }
    // { sinner: "Rodion", idName: "", image: "IDs/Rodion/_Rodion.webp", portrait: "IDs/Rodion/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const sinclairIDs = [
    { sinner: "Sinclair", idName: "LCB Sinner", image: "IDs/Sinclair/LCB_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/LCB_Sinclair.jpg",
        quote: "I'm Sinclair… Emil Sinclair. Oh, my number is, uhm… eleven.", skills: sinclairskillData.LCBSinclair, voiceline: "IDs/Sinclair/Voicelines/LCB.wav", rarity: "Ø" },
    { sinner: "Sinclair", idName: "Lobotomy E.G.O::Red Sheet", image: "IDs/Sinclair/Red_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Red_Sinclair.jpg",
        quote: "For the liberation... I'll bear this, even if it's a curse.", skills: sinclairskillData.RedSinclair, voiceline: "IDs/Sinclair/Voicelines/Red.wav", rarity: "ØØ" },
    { sinner: "Sinclair", idName: "Los Mariachis Jefe", image: "IDs/Sinclair/Jefe_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Jefe_Sinclair.jpg",
        quote: "I'll repay you with merrier music.", skills: sinclairskillData.JefeSinclair, voiceline: "IDs/Sinclair/Voicelines/Jefe.wav", rarity: "ØØ" },
    { sinner: "Sinclair", idName: "Molar Boatworks fixer", image: "IDs/Sinclair/Molar_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Molar_Sinclair.jpg",
        quote: "The upgrade certainly improved the output... but it kinda feels redundant if all I'm doing with it is catching more crabs.",
        skills: sinclairskillData.MolarSinclair, voiceline: "IDs/Sinclair/Voicelines/Molar.wav", rarity: "ØØ" },
    { sinner: "Sinclair", idName: "Zwei Assoc. South Section 6", image: "IDs/Sinclair/ZweiS_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/ZweiS_Sinclair.jpg",
        quote: "I'll work even harder! I'll be sure not to let you down.", skills: sinclairskillData.ZweiSSinclair, voiceline: "IDs/Sinclair/Voicelines/ZweiS.wav", rarity: "ØØ" },
    { sinner: "Sinclair", idName: "Zwei Assoc. West Section 3", image: "IDs/Sinclair/ZweiW_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/ZweiW_Sinclair.jpg",
        quote: "Don't worry. You're my target… so I'll protect you no matter what.", skills: sinclairskillData.ZweiWSinclair, voiceline: "IDs/Sinclair/Voicelines/ZweiW.ogg", rarity: "ØØ" },
    { sinner: "Sinclair", idName: "Blade Lineage Salsu", image: "IDs/Sinclair/BL_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/BL_Sinclair.jpg",
        quote: "I'll become a sharper blade.", skills: sinclairskillData.BladeSinclair, voiceline: "IDs/Sinclair/Voicelines/Blade.wav", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "Cinq Assoc. South Section 4 Director", image: "IDs/Sinclair/Cinq_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Cinq_Sinclair.jpg",
        quote: "I'll show you impeccable focus. Though you will never see as I do.", skills: sinclairskillData.CinqSinclair, voiceline: "IDs/Sinclair/Voicelines/Cinq.ogg", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "Dawn Office Fixer", image: "IDs/Sinclair/Dawn_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Dawn_Sinclair.jpg",
        quote: "No one's going to shed their tears on behalf of my sorrow.", skills: sinclairskillData.DawnSinclair, voiceline: "IDs/Sinclair/Voicelines/Dawn.wav", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "Devyat' Assoc. North Section 3", image: "IDs/Sinclair/Devyat_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Devyat_Sinclair.jpg",
        quote: "Ugh, I really hoped it wouldn't have to come to this, but I need to get there in time…! Poludnitsa, engage mode conversion!",
        skills: sinclairskillData.DevyatSinclair, voiceline: "IDs/Sinclair/Voicelines/Devyat.ogg", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "Heishou Pack - You Branch", image: "IDs/Sinclair/Heishou_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Heishou_Sinclair.jpg",
        quote: "There's nothing unfair about the way you're going out. It's not bad luck or the lord's disfavor that killed you here today. It's your weakness.",
        skills: sinclairskillData.HeishouSinclair, voiceline: "IDs/Sinclair/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "The House of Spiders: The Pinky Apprentice", image: "IDs/Sinclair/Pinky_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Pinky_Sinclair.jpg",
        quote: "A rare assignment my master has bestowed upon me. I shall treasure this chance, so as not to cast shame upon the Moonlit Azure Blade (月下靑刀) my master has imparted unto me.",
        skills: sinclairskillData.PinkySinclair, voiceline: "IDs/Sinclair/Voicelines/Pinky.wav", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "The Middle Little Brother", image: "IDs/Sinclair/Middle_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Middle_Sinclair.jpg",
        quote: "Aha… Yeah, yeah. Pipe down, one at a time. Where's Big Brother headed to again?", skills: sinclairskillData.MiddleSinclair, voiceline: "IDs/Sinclair/Voicelines/Middle.ogg", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "The One Who Shall Grip", image: "IDs/Sinclair/Grip_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Grip_Sinclair.jpg",
        quote: "This doesn't really feel special. I have... always had talent... as the chosen one.", skills: sinclairskillData.NCorpSinclair, voiceline: "IDs/Sinclair/Voicelines/NCorp.wav", rarity: "ØØØ" },
    { sinner: "Sinclair", idName: "The Thumb East Soldato II", image: "IDs/Sinclair/Thumb_Sinclair.webp", portrait: "IDs/Sinclair/Portraits/Thumb_Sinclair.jpg",
        quote: "Daring to breathe when you haven't even followed the underboss's command? Now that's quite discourteous.", skills: sinclairskillData.ThumbSinclair, voiceline: "IDs/Sinclair/Voicelines/Thumb.wav", rarity: "ØØØ" }
    // { sinner: "Sinclair", idName: "", image: "IDs/Sinclair/.webp", portrait: "IDs/Sinclair/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const outisIDs = [
    { sinner: "Outis", idName: "LCB Sinner", image: "IDs/Outis/LCB_Outis.webp", portrait: "IDs/Outis/Portraits/LCB_Outis.jpg",
        quote: "My name is Outis. I hope you'll remember it well.", skills: outisskillData.LCBOutis, voiceline: "IDs/Outis/Voicelines/LCB.wav", rarity: "ØØ" },
    { sinner: "Outis", idName: "Blade Lineage Salsu", image: "IDs/Outis/BL_Outis.webp", portrait: "IDs/Outis/Portraits/BL_Outis.jpg",
        quote: "If you so wish... I shall serve you.", skills: outisskillData.BladeOutis, voiceline: "IDs/Outis/Voicelines/Blade.wav", rarity: "ØØ" },
    { sinner: "Outis", idName: "Cinq Assoc. South Section 4", image: "IDs/Outis/Cinq_Outis.webp", portrait: "IDs/Outis/Portraits/Cinq_Outis.jpg",
        quote: "Yes, it is an honor to be acknowledged by you. I will not disappoint.", skills: outisskillData.CinqOutis, voiceline: "IDs/Outis/Voicelines/Cinq.ogg", rarity: "ØØ" },
    { sinner: "Outis", idName: "G Corp. Head Manager", image: "IDs/Outis/GCorp_Outis.webp", portrait: "IDs/Outis/Portraits/GCorp_Outis.jpg",
        quote: "Salutations. I shall do my utmost to serve.", skills: outisskillData.GCorpOutis, voiceline: "IDs/Outis/Voicelines/GCorp.wav", rarity: "ØØ" },
    { sinner: "Outis", idName: "The Ring Pointillist Student", image: "IDs/Outis/Ring_Outis.webp", portrait: "IDs/Outis/Portraits/Ring_Outis.jpg",
        quote: "Do you understand the allure of contours of light and shadow? The beauty born from countless collections of dots? No? Then allow me to enlighten you.",
        skills: outisskillData.RingOutis, voiceline: "IDs/Outis/Voicelines/Ring.ogg", rarity: "ØØ" },
    { sinner: "Outis", idName: "The Barber of La Manchaland", image: "IDs/Outis/Barber_Outis.webp", portrait: "IDs/Outis/Portraits/Barber_Outis.jpg",
        quote: "How are the preparations for the Parade going? Costumes? Stage prop? Haah… you lazy bums. I will take over the final review of the preparations!",
        skills: outisskillData.BarberOutis, voiceline: "IDs/Outis/Voicelines/Barber.ogg", rarity: "ØØØ" },
    { sinner: "Outis", idName: "Heishou Pack - Mao Branch", image: "IDs/Outis/Heishou_Outis.webp", portrait: "IDs/Outis/Portraits/Heishou_Outis.jpg",
        quote: "Your foe has been eliminated. To where must I hop next?", skills: outisskillData.HeishouOutis, voiceline: "IDs/Outis/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Outis", idName: "The House of Spiders: The Middle Nursefather", image: "IDs/Outis/Middle_Outis.webp", portrait: "IDs/Outis/Portraits/Middle_Outis.jpg",
        quote: "... Good girl!", skills: outisskillData.MiddleOutis, voiceline: "IDs/Outis/Voicelines/Middle.wav", rarity: "ØØØ" },
    { sinner: "Outis", idName: "LCA Udjat Vanguard Team 3 Leader", image: "IDs/Outis/LCA_Outis.webp", portrait: "IDs/Outis/Portraits/LCA_Outis.jpg",
        quote: "Udjat Khamsa, Sitta, maneuver to our left with me. Udjat Talata, Ashara, circumnavigate the building to its back entrance. Remaining units, hold this position. Maintain pressure at will on the target.",
        skills: outisskillData.LCAOutis, voiceline: "IDs/Outis/Voicelines/LCA.wav", rarity: "ØØØ" },
    { sinner: "Outis", idName: "Lobotomy E.G.O::Magic Bullet", image: "IDs/Outis/Magic_Outis.webp", portrait: "IDs/Outis/Portraits/Magic_Outis.jpg",
        quote: "I remember the day when it offered me the contract.", skills: outisskillData.MagicOutis, voiceline: "IDs/Outis/Voicelines/Magic.wav", rarity: "ØØØ" },
    { sinner: "Outis", idName: "Molar Office Fixer", image: "IDs/Outis/Molar_Outis.webp", portrait: "IDs/Outis/Portraits/Molar_Outis.jpg",
        quote: "Do I really need to get involved in this...? But since you're asking nicely, sure.", skills: outisskillData.MolarOutis, voiceline: "IDs/Outis/Voicelines/Molar.wav", rarity: "ØØØ" },
    { sinner: "Outis", idName: "Seven Assoc. South Section 6 Director", image: "IDs/Outis/Seven_Outis.webp", portrait: "IDs/Outis/Portraits/Seven_Outis.jpg",
        quote: "This means more fieldwork for me, doesn't it... Well, fine. I won't turn down additional experience.", skills: outisskillData.SevenOutis, voiceline: "IDs/Outis/Voicelines/Seven.wav", rarity: "ØØØ" },
    { sinner: "Outis", idName: "T Corp. Class 3 VDCU Staff", image: "IDs/Outis/TCorp_Outis.webp", portrait: "IDs/Outis/Portraits/TCorp_Outis.jpg",
        quote: "You made me drop my hat… impressive. T-3 Repossessor Model - Mace, engage max activation.", skills: outisskillData.TCorpOutis, voiceline: "IDs/Outis/Voicelines/TCorp.wav", rarity: "ØØØ" },
    { sinner: "Outis", idName: "W Corp. L3 Cleanup Captain", image: "IDs/Outis/WCorp_Outis.webp", portrait: "IDs/Outis/Portraits/WCorp_Outis.jpg",
        quote: "The homeward journey is…! Agh… it's still tumultuous.", skills: outisskillData.WCorpOutis, voiceline: "IDs/Outis/Voicelines/WCorp.ogg", rarity: "ØØØ" },
    { sinner: "Outis", idName: "Wuthering Heights Chief Butler", image: "IDs/Outis/Butler_Outis.webp", portrait: "IDs/Outis/Portraits/Butler_Outis.jpg",
        quote: "Ah, a gift from the Mistress of the manor. I most graciously accept her offering.", skills: outisskillData.ButlerOutis, voiceline: "IDs/Outis/Voicelines/Butler.wav", rarity: "ØØØ" }
    // { sinner: "Outis", idName: "", image: "IDs/Outis/_Outis.webp", portrait: "IDs/Outis/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
export const gregorIDs = [
    { sinner: "Gregor", idName: "LCB Sinner", image: "IDs/Gregor/LCB_Gregor.webp", portrait: "IDs/Gregor/Portraits/LCB_Gregor.jpg",
        quote: "Mm... It's Gregor. Well, feel free to talk to me unless I'm asleep.", skills: gregorskillData.LCBGregor, voiceline: "IDs/Gregor/Voicelines/LCB.ogg", rarity: "Ø" },
    { sinner: "Gregor", idName: "Kurokumo Clan Captain", image: "IDs/Gregor/Kurokumo_Gregor.webp", portrait: "IDs/Gregor/Portraits/Kurokumo_Gregor.jpg",
        quote: "Hooah... My mind's clearer than ever, man. And with this delicious cig... I'd say I'm in peak physical shape... to wreck shop.",
        skills: gregorskillData.KurokumoGregor, voiceline: "IDs/Gregor/Voicelines/Kurokumo.ogg", rarity: "ØØ" },
    { sinner: "Gregor", idName: "Liu Assoc. South Section 6", image: "IDs/Gregor/Liu_Gregor.webp", portrait: "IDs/Gregor/Portraits/Liu_Gregor.jpg",
        quote: "C'mon, I don't need all this. You're pressuring me into working harder.", skills: gregorskillData.LiuGregor, voiceline: "IDs/Gregor/Voicelines/Liu.ogg", rarity: "ØØ" },
    { sinner: "Gregor", idName: "R.B. Sous-chef", image: "IDs/Gregor/RB_Gregor.webp", portrait: "IDs/Gregor/Portraits/RB_Gregor.jpg",
        quote: "Me...? Ha, guess you do know who the real chef is here, huh...?", skills: gregorskillData.RBGregor, voiceline: "IDs/Gregor/Voicelines/RB.ogg", rarity: "ØØ" },
    { sinner: "Gregor", idName: "Rosespanner Workshop Fixer", image: "IDs/Gregor/Rosespanner_Gregor.webp", portrait: "IDs/Gregor/Portraits/Rosespanner_Gregor.jpg",
        quote: "Oh, erm... I wasn't planning to stay here for long... You gonna take the responsibility?", skills: gregorskillData.RosespannerGregor, voiceline: "IDs/Gregor/Voicelines/Rosespanner.ogg", rarity: "ØØ" },
    { sinner: "Gregor", idName: "Dawn Office Rep", image: "IDs/Gregor/Dawn_Gregor.png", portrait: "IDs/Gregor/Portraits/Dawn_Gregor.png",
        quote: "... *puff* Well, I hope you weren't looking forward to a peaceful end after imbruing your hands in so much blood. Gird your loins, rookie. It's about to get real.",
        skills: gregorskillData.DawnGregor, voiceline: "IDs/Gregor/Voicelines/Dawn.wav", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "Edgar Family Heir", image: "IDs/Gregor/Edgar_Gregor.webp", portrait: "IDs/Gregor/Portraits/Edgar_Gregor.jpg",
        quote: "Yes… it's about time I sharpened the blade of my sword.", skills: gregorskillData.EdgarGregor, voiceline: "IDs/Gregor/Voicelines/Edgar.mp3", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "Firefist Office Survivor", image: "IDs/Gregor/Firefist_Gregor.webp", portrait: "IDs/Gregor/Portraits/Firefist_Gregor.jpg",
        quote: "It's a cold, cold City, bud… Let's at least have the decency to serve revenge piping hot.",
        skills: gregorskillData.FirefistGregor, voiceline: "IDs/Gregor/Voicelines/Firefist.wav", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "G Corp. Manager Corporal", image: "IDs/Gregor/GCorp_Gregor.webp", portrait: "IDs/Gregor/Portraits/GCorp_Gregor.jpg",
        quote: "Salutations! I'll continue to aid you to the best of my ability, Manager!", skills: gregorskillData.GCorpGregor, voiceline: "IDs/Gregor/Voicelines/GCorp.wav", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "Heishou Pack - Si Branch", image: "IDs/Gregor/Heishou_Gregor.webp", portrait: "IDs/Gregor/Portraits/Heishou_Gregor.jpg",
        quote: "Hey, no point in looking around for a way out. I'm all coiled up now, ready to strike. You're not getting out of this.",
        skills: gregorskillData.HeishouGregor, voiceline: "IDs/Gregor/Voicelines/Heishou.wav", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "LCE E.G.O::AEDD", image: "IDs/Gregor/LCE_Gregor.webp", portrait: "IDs/Gregor/Portraits/LCE_Gregor.jpg",
        quote: "Activating structural analyzer... Mm. It's operational. Alright, drill that shape into your heads, because if I flip a tail with the Monolith... this may very well be what I become.Take a good look at the vulnerabilities now, so you can take me out in one fell swoop later. Got it?",
        skills: gregorskillData.LCEGregor, voiceline: "IDs/Gregor/Voicelines/LCE.wav", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "Lobotomy E.G.O::Lamp", image: "IDs/Gregor/Lamp_Gregor.webp", portrait: "IDs/Gregor/Portraits/Lamp_Gregor.jpg",
        quote: "I can see everything with utter clarity, no matter the distance—things I couldn't see before, things that were shrouded in shadows. … That's enough testing. It's obvious that I have enough aptitude to wield both this E.G.O and the Gift at the same time.",
        skills: gregorskillData.LampGregor, voiceline: "IDs/Gregor/Voicelines/Lamp.wav", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "Night Awls Capitano", image: "IDs/Gregor/Night_Gregor.webp", portrait: "IDs/Gregor/Portraits/Night_Gregor.jpg",
        quote: "The Index, W Corp., Shi Association... They're using all kinds of techniques, just as I've heard. Still, whoever you're up against, there's always a gap to strike through. There's still hope... We might just come out of this alive yet.",
        skills: gregorskillData.NightGregor, voiceline: "IDs/Gregor/Voicelines/Night.wav", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "The Priest of La Manchaland", image: "IDs/Gregor/Priest_Gregor.webp", portrait: "IDs/Gregor/Portraits/Priest_Gregor.jpg",
        quote: "Though this shame may be masked… the thirst underneath its surface won't leave me alone.", skills: gregorskillData.PriestGregor, voiceline: "IDs/Gregor/Voicelines/Priest.ogg", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "Twinhook Pirates First Mate", image: "IDs/Gregor/Twinhook_Gregor.webp", portrait: "IDs/Gregor/Portraits/Twinhook_Gregor.jpg",
        quote: "You wanna work together? Hmm~ Well, sure, I think you'll do. Well, then... let's make this work.", skills: gregorskillData.TwinhookGregor, voiceline: "IDs/Gregor/Voicelines/Twinhook.ogg", rarity: "ØØØ" },
    { sinner: "Gregor", idName: "Zwei Assoc. South Section 4", image: "IDs/Gregor/Zwei_Gregor.webp", portrait: "IDs/Gregor/Portraits/Zwei_Gregor.jpg",
        quote: "My time to shine, huh? Let me be your shield!", skills: gregorskillData.ZweiGregor, voiceline: "IDs/Gregor/Voicelines/Zwei.wav", rarity: "ØØØ" }
    // { sinner: "Gregor", idName: "", image: "IDs/Gregor/_Gregor.webp", portrait: "IDs/Gregor/Portraits/", quote: "", voiceline: "", rarity: "ØØØ" } For future use
];
